# Preparando o ambiente

## Importação de Bibliotecas

In [1]:
#install
#!pip install -q -U duckdb matplotlib numpy pandas plotly scikit-learn scipy seaborn shap statsmodels xgboost

In [ ]:
#imports
import pandas as pd
import numpy as np
import os

## Obtenção das tabelas e dados

In [3]:
pasta_dos_csv = '1-datasets/'

for nome_do_arquivo in os.listdir(pasta_dos_csv):
    if nome_do_arquivo.endswith('.csv'):
        caminho_do_arquivo = os.path.join(pasta_dos_csv, nome_do_arquivo)
        variavel_nome = nome_do_arquivo.replace('.csv', '').replace('-','_').replace(' ', '_')
        try:
            globals()[f'dataset_{variavel_nome}'] = pd.read_csv(caminho_do_arquivo, sep=';')
        except Exception as e:
            print(f'Falha no carregamento no arquivo {nome_do_arquivo}: {e}')

Falha no carregamento no arquivo Produtos_clear.csv: Error tokenizing data. C error: Expected 1 fields in line 2467, saw 2


**O que está bem feito:**
- `os.path.join` — portável entre Windows, Mac e Linux
- `.endswith('.csv')` — não tenta ler outros tipos de arquivo
- `replace('-', '_')` e `replace(' ', '_')` — garante nomes de variável válidos em Python
- `try/except` — se um arquivo estiver corrompido, o loop continua

**Resultado esperado:**

# Análise Exploratória de Dados (EDA)

In [4]:
def eda_report(df, nome='DataFrame'):
    print(f"{'='*40}")
    print(f"EDA Report: {nome}")
    print(f"{'='*40}")
    # Colunas e Linhas
    print(f"\nColunas: {df.shape[1]}")
    print(f"Linhas:  {df.shape[0]}")
    # Dtypes
    print(f"\nDtypes:")
    print(f"  str:   {len(df.select_dtypes(include=['str','object']).columns)}")
    print(f"  int:   {len(df.select_dtypes(include='int').columns)}")
    print(f"  float: {len(df.select_dtypes(include='float').columns)}")
    print(f"  data:  {len(df.select_dtypes(include='datetime').columns)}")
    # Non-Null
    print(f"\nNon-Null:")
    for col in df.columns:
        print(f"  {col}: {df[col].notnull().sum()}")
    # Unique
    print(f"\nUnique:")
    for col in df.columns:
        print(f"  {col}: {df[col].nunique()}")
    # Duplicatas
    print(f"\nDados Duplicados: {df.duplicated().sum()}")
    print(f"{'='*40}")

### Clientes

In [5]:
dataset_Clientes.head(2)

,ID Cliente,Nome Cliente,Segmento,Cidade,Estado,Pais,Mercado,Regiao
0,RH-19495,Rick Hansen,Consumidor,New York City,New York,United States,US,East
1,JR-16210,Justin Ritter,Corporativo,Wollongong,New South Wales,Australia,APAC,Oceania

In [6]:
dataset_Clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 1590 entries, 0 to 1589
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID Cliente    1590 non-null   str
 1   Nome Cliente  1590 non-null   str
 2   Segmento      1590 non-null   str
 3   Cidade        1590 non-null   str
 4   Estado        1590 non-null   str
 5   Pais          1590 non-null   str
 6   Mercado       1590 non-null   str
 7   Regiao        1590 non-null   str
dtypes: str(8)
memory usage: 99.5 KB

In [7]:
dataset_Clientes.describe(include=[str])

,ID Cliente,Nome Cliente,Segmento,Cidade,Estado,Pais,Mercado,Regiao
count,1590,1590,1590,1590,1590,1590,1590,1590
unique,1590,795,3,860,536,122,7,13
top,RH-19495,Rick Hansen,Consumidor,New York City,California,United States,EMEA,EMEA
freq,1,2,818,28,35,173,385,385

In [8]:
dataset_Clientes.duplicated().sum()

np.int64(0)

In [9]:
eda_report(dataset_Clientes, nome='Clientes')

========================================
EDA Report: Clientes
========================================

Colunas: 8
Linhas:  1590

Dtypes:
  str:   8
  int:   0
  float: 0
  data:  0

Non-Null:
  ID Cliente: 1590
  Nome Cliente: 1590
  Segmento: 1590
  Cidade: 1590
  Estado: 1590
  Pais: 1590
  Mercado: 1590
  Regiao: 1590

Unique:
  ID Cliente: 1590
  Nome Cliente: 795
  Segmento: 3
  Cidade: 860
  Estado: 536
  Pais: 122
  Mercado: 7
  Regiao: 13

Dados Duplicados: 0
========================================

### Pedidos

In [10]:
dataset_Pedidos.head(2)

        ID Pedido Data Pedido  Data Envio Modo Envio Prioridade Pedido
0  CA-2012-124891  31-07-2012  31-07-2012  Mesmo Dia           Critico
1  CA-2012-124891  31-07-2012  31-07-2012  Mesmo Dia           Critico

In [11]:
dataset_Pedidos.info()

<class 'pandas.DataFrame'>
RangeIndex: 25036 entries, 0 to 25035
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID Pedido          25036 non-null  str
 1   Data Pedido        25036 non-null  str
 2   Data Envio         25036 non-null  str
 3   Modo Envio         25036 non-null  str
 4   Prioridade Pedido  25036 non-null  str
dtypes: str(5)
memory usage: 978.1 KB

In [12]:
dataset_Pedidos.describe()

,ID Pedido,Data Pedido,Data Envio,Modo Envio,Prioridade Pedido
count,25036,25036,25036,25036,25036
unique,25035,1428,1464,4,4
top,CA-2012-124891,18-06-2014,22-11-2014,Classe Padrao,Medio
freq,2,59,54,14953,14281

In [13]:
eda_report(dataset_Pedidos, nome='Pedidos')

========================================
EDA Report: Pedidos
========================================

Colunas: 5
Linhas:  25036

Dtypes:
  str:   5
  int:   0
  float: 0
  data:  0

Non-Null:
  ID Pedido: 25036
  Data Pedido: 25036
  Data Envio: 25036
  Modo Envio: 25036
  Prioridade Pedido: 25036

Unique:
  ID Pedido: 25035
  Data Pedido: 1428
  Data Envio: 1464
  Modo Envio: 4
  Prioridade Pedido: 4

Dados Duplicados: 1
========================================

**Data Pedido** > Formato Data *dd-mm-yyyy*

**Data Envio** > Formato Data  *dd-mm-yyyy*

### Produtos

In [14]:
dataset_Produtos.head(2)

,ID Produto,Categoria,SubCategoria,Nome Produto
0,TEC-AC-10003033,Tecnologia,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...
1,TEC-AC-10003033,Tecnologia,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...

In [15]:
dataset_Produtos.info()

<class 'pandas.DataFrame'>
RangeIndex: 10293 entries, 0 to 10292
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID Produto    10293 non-null  str
 1   Categoria     10293 non-null  str
 2   SubCategoria  10293 non-null  str
 3   Nome Produto  10293 non-null  str
dtypes: str(4)
memory usage: 321.8 KB

In [16]:
dataset_Produtos.describe()

             ID Produto               Categoria SubCategoria Nome Produto
count             10293                   10293        10293        10293
unique            10292                       3           17         3660
top     TEC-AC-10003033  Material de Escritorio        Paper      Staples
freq                  2                    5689          781           45

In [17]:
eda_report(dataset_Produtos, nome='Produtos')

========================================
EDA Report: Produtos
========================================

Colunas: 4
Linhas:  10293

Dtypes:
  str:   4
  int:   0
  float: 0
  data:  0

Non-Null:
  ID Produto: 10293
  Categoria: 10293
  SubCategoria: 10293
  Nome Produto: 10293

Unique:
  ID Produto: 10292
  Categoria: 3
  SubCategoria: 17
  Nome Produto: 3660

Dados Duplicados: 1
========================================

### Vendas

In [18]:
dataset_Vendas.head(2)

,Pedido,Cliente,Produto,Valor Venda,Quantidade Vendida,Custo Envio
0,CA-2012-124891,RH-19495,TEC-AC-10003033,"2309,65",7,"933,57"
1,IN-2013-77878,JR-16210,FUR-CH-10003950,"3709,395",9,"923,63"

In [19]:
dataset_Vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Pedido              51290 non-null  str
 1   Cliente             51290 non-null  str
 2   Produto             51290 non-null  str
 3   Valor Venda         51290 non-null  str
 4   Quantidade Vendida  51290 non-null  int64
 5   Custo Envio         51290 non-null  str
dtypes: int64(1), str(5)
memory usage: 2.3 MB

In [20]:
dataset_Vendas.describe()

       Quantidade Vendida
count        51290.000000
mean             3.476545
std              2.278766
min              1.000000
25%              2.000000
50%              3.000000
75%              5.000000
max             14.000000

In [21]:
dataset_Vendas.describe(include=[str])

                Pedido   Cliente          Produto Valor Venda Custo Envio
count            51290     51290            51290       51290       51290
unique           25035      1590            10292       22995       10037
top     CA-2014-100111  PO-18850  OFF-AR-10003651       12,96        0,86
freq                14        97               35          66          76

In [22]:
eda_report(dataset_Vendas,nome='Vendas')

========================================
EDA Report: Vendas
========================================

Colunas: 6
Linhas:  51290

Dtypes:
  str:   5
  int:   1
  float: 0
  data:  0

Non-Null:
  Pedido: 51290
  Cliente: 51290
  Produto: 51290
  Valor Venda: 51290
  Quantidade Vendida: 51290
  Custo Envio: 51290

Unique:
  Pedido: 25035
  Cliente: 1590
  Produto: 10292
  Valor Venda: 22995
  Quantidade Vendida: 14
  Custo Envio: 10037

Dados Duplicados: 0
========================================

**Valor Venda** > Formato Float

**Custo Envio** > Formato Float

# Limpeza dos Dataset

In [23]:
for nome_da_variavel in ['Clientes','Pedidos','Produtos','Vendas']:
    try:
        globals()[f'dataset_{nome_da_variavel}_limpeza'] = globals()[f'dataset_{nome_da_variavel}']
    except Exception as e:
        print(f'Falha na criação da variavel Global {nome_da_variavel}: {e}')

In [24]:
dataset_Clientes_limpeza.head(1)

,ID Cliente,Nome Cliente,Segmento,Cidade,Estado,Pais,Mercado,Regiao
0,RH-19495,Rick Hansen,Consumidor,New York City,New York,United States,US,East

## Correção dos tipos de dados

In [25]:
dataset_Vendas_limpeza.head(1)

,Pedido,Cliente,Produto,Valor Venda,Quantidade Vendida,Custo Envio
0,CA-2012-124891,RH-19495,TEC-AC-10003033,"2309,65",7,"933,57"

In [26]:
for coluna in ['Valor Venda', 'Custo Envio']:
    dataset_Vendas_limpeza[coluna] = pd.to_numeric(dataset_Vendas_limpeza[coluna].str.replace('.','',regex=False).str.replace(',','.',regex=False), errors='coerce')

In [27]:
dataset_Vendas_limpeza.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Pedido              51290 non-null  str
 1   Cliente             51290 non-null  str
 2   Produto             51290 non-null  str
 3   Valor Venda         51290 non-null  float64
 4   Quantidade Vendida  51290 non-null  int64
 5   Custo Envio         51290 non-null  float64
dtypes: float64(2), int64(1), str(3)
memory usage: 2.3 MB

In [28]:
dataset_Vendas_limpeza.head(1)

,Pedido,Cliente,Produto,Valor Venda,Quantidade Vendida,Custo Envio
0,CA-2012-124891,RH-19495,TEC-AC-10003033,2309.65,7,933.57

## Tratamento de Valores NaN

## Tratamento de Valores Duplicados

In [29]:
dataset_Pedidos_limpeza.drop_duplicates(inplace=True)
dataset_Pedidos_limpeza.duplicated().sum()

np.int64(0)

In [30]:
dataset_Produtos_limpeza.drop_duplicates(inplace=True)
dataset_Produtos_limpeza.duplicated().sum()

np.int64(0)

## Tratamento de Dados Outliers

# Criando Novo arquivo csv para gerar o dashboard

In [31]:
for nome_da_variavel in ['Clientes','Pedidos','Produtos','Vendas']:
    try:
        globals()[f'dataset_{nome_da_variavel}_limpeza'].to_csv(f'1-datasets/{nome_da_variavel}_clear.csv', index=False, encoding='utf-8')
    except Exception as e:
        print(f'Falha na criação da variavel Global {nome_da_variavel}: {e}')